"use client";
import {useSearchParams} from "next/navigation";import Link from "next/link";import {Suspense,useEffect,useMemo,useState} from "react";
type Item={key:string;product:{name:string;price:number};qty:number;variant:string;addons:{name:string;price:number}[]};
function CheckoutContent(){
 const q=useSearchParams();const mode=q.get("mode")||"TAKE_AWAY";const[cart,setCart]=useState<Item[]>([]);const[outlet,setOutlet]=useState("Jakarta");const[done,setDone]=useState(false);
 const[name,setName]=useState("");const[wa,setWa]=useState("");const[payment,setPayment]=useState("QRIS");const[date,setDate]=useState("");const[time,setTime]=useState("");const[address,setAddress]=useState("");const[note,setNote]=useState("");
 useEffect(()=>{try{setCart(JSON.parse(sessionStorage.getItem("otc_cart")||"[]"));setOutlet(sessionStorage.getItem("otc_outlet")||"Jakarta")}catch{}},[]);
 const total=useMemo(()=>cart.reduce((n,i)=>n+(i.product.price+i.addons.reduce((a,x)=>a+x.price,0))*i.qty,0),[cart]);const label=mode==="TAKE_AWAY"?"TAKE AWAY":mode==="PRE_ORDER"?"PRE-ORDER":"DELIVERY";
 if(done)return <main className="otc-page"><section className="success-card"><span className="eyebrow">ORDER CREATED</span><h1>Pesanan berhasil.</h1><p>Order <b>OTC-00124</b> tercatat di <b>{outlet}</b>. Status awal: PAID.</p><div className="receipt-mini"><span>Fulfillment</span><b>{label}</b><span>Total</span><b>Rp {total.toLocaleString("id-ID")}</b><span>Pickup / Handover Pass</span><b>7K9P</b></div><p className="muted">{mode==="PRE_ORDER"?"Jadwal: "+date+" · "+time:mode==="DELIVERY"?"Order akan diproses dan diserahkan ke kurir pihak ketiga setelah READY.":"Pickup setelah READY di outlet."}</p><Link className="otc-primary" href="/otc/digital-receipt">Lihat Digital Receipt →</Link></section></main>;
 return <main className="otc-page"><header className="otc-head"><div><b>NORTAGO OTC</b><small>Checkout · {outlet}</small></div><Link href="/otc/customer-order">← Menu</Link></header><section className="customer-title"><span>CHECKOUT</span><h1>{label}</h1><p>Checkout menyesuaikan fulfillment yang dipilih.</p></section>
 <form className="checkout-grid" onSubmit={e=>{e.preventDefault();setDone(true)}}><div className="form-card"><h2>Customer & Fulfillment</h2><label>Nama<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>WhatsApp<input value={wa} onChange={e=>setWa(e.target.value)} placeholder="08xxxxxxxxxx" required/></label>
 {mode==="PRE_ORDER"&&<div className="two"><label>Tanggal pickup<input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label><label>Jam pickup<input type="time" value={time} onChange={e=>setTime(e.target.value)} required/></label></div>}
 {mode==="DELIVERY"&&<><label>Alamat delivery<textarea value={address} onChange={e=>setAddress(e.target.value)} required/></label><label>Catatan delivery<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Patokan / instruksi untuk kurir"/></label><div className="info-box">Kurir adalah pihak ketiga. OCT mencatat order dan handover, bukan dispatch armada.</div></>}
 {mode==="TAKE_AWAY"&&<div className="info-box">Pickup Pass akan menjadi kode verifikasi single-use.</div>}
 <h3>Ringkasan item</h3>{cart.map(i=><div className="cart-line" key={i.key}><span>{i.product.name} × {i.qty}<small style={{display:"block",color:"#617b76"}}>{i.variant}</small></span><b>Rp {((i.product.price+i.addons.reduce((a,x)=>a+x.price,0))*i.qty).toLocaleString("id-ID")}</b></div>)}</div>
 <div className="form-card"><h2>Pembayaran</h2><label>Metode<select value={payment} onChange={e=>setPayment(e.target.value)}><option>QRIS</option><option>Cash</option><option>Other</option></select></label><div className="summary"><span>Total order</span><strong>Rp {total.toLocaleString("id-ID")}</strong></div><button className="otc-primary full" disabled={!cart.length}>Bayar & Buat Pesanan →</button><small className="muted">Gateway pembayaran dapat diintegrasikan kemudian. Demo ini mencatat metode pembayaran yang dipilih.</small></div></form><footer>Supported by NORTAGO · Digital transaction record</footer></main>
}
export default function Checkout(){return <Suspense fallback={<main className="otc-page"><div className="loading">Memuat checkout…</div></main>}><CheckoutContent/></Suspense>}
