"use client";
export const dynamic = "force-dynamic";

import { useEffect, useState } from "react";
import { createClient, type User } from "@supabase/supabase-js";

function getSupabase(){return createClient(process.env.NEXT_PUBLIC_SUPABASE_URL || "https://placeholder.supabase.co", process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "placeholder-anon-key")}
const money=(n:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n);

export default function ProcurementCafe(){
 const supabase=getSupabase();
 const [user,setUser]=useState<User|null>(null),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 const [businessId,setBusinessId]=useState(""),[businessName,setBusinessName]=useState(""),[outletId,setOutletId]=useState(""),[outletName,setOutletName]=useState("");
 const [tab,setTab]=useState("dashboard"),[items,setItems]=useState<any[]>([]),[suppliers,setSuppliers]=useState<any[]>([]),[requests,setRequests]=useState<any[]>([]),[requestItems,setRequestItems]=useState<any[]>([]),[pos,setPos]=useState<any[]>([]),[stocks,setStocks]=useState<any[]>([]);
 const [showItem,setShowItem]=useState(false),[showSupplier,setShowSupplier]=useState(false),[showRequest,setShowRequest]=useState(false),[showPO,setShowPO]=useState(false);
 const [newItem,setNewItem]=useState({name:"",category:"Bahan Baku",unit:"kg",reorder_point:"0",last_cost:"0"});
 const [newSupplier,setNewSupplier]=useState({name:"",phone:"",lead_time_days:"1"});
 const [reqItem,setReqItem]=useState(""),[reqQty,setReqQty]=useState(""),[reqDate,setReqDate]=useState(""),[reqNote,setReqNote]=useState(""); const [poRequest,setPoRequest]=useState(""),[poSupplier,setPoSupplier]=useState(""),[poCosts,setPoCosts]=useState<Record<string,string>>({}),[poExpected,setPoExpected]=useState(""),[poNote,setPoNote]=useState("");

 useEffect(()=>{getSupabase().auth.getSession().then(({data})=>{setUser(data.session?.user??null);if(data.session?.user)load(data.session.user);else setLoading(false)});const {data:{subscription}}=getSupabase().auth.onAuthStateChange((_e,s)=>{setUser(s?.user??null);if(s?.user)load(s.user)});return()=>subscription.unsubscribe()},[]);

 async function load(u:User){
  setLoading(true);setError("");
  const {data:bu,error:e}=await getSupabase().from("business_users").select("business_id").eq("user_id",u.id).limit(1).maybeSingle();
  if(e||!bu){setError(e?.message??"Akun belum terhubung ke bisnis.");setLoading(false);return}
  setBusinessId(bu.business_id);
  const [b,o,it,s,r,ri,p,st]=await Promise.all([
   getSupabase().from("businesses").select("name").eq("id",bu.business_id).maybeSingle(),
   getSupabase().from("otc_outlets").select("id,name").eq("business_id",bu.business_id).eq("is_active",true).limit(1).maybeSingle(),
   getSupabase().from("proc_items").select("id,name,category,unit,reorder_point,last_cost").eq("business_id",bu.business_id).eq("is_active",true).order("name"),
   getSupabase().from("proc_suppliers").select("id,name,phone,lead_time_days").eq("business_id",bu.business_id).eq("is_active",true).order("name"),
   getSupabase().from("proc_requests").select("id,status,needed_date,notes,created_at,outlet_id").eq("business_id",bu.business_id).order("created_at",{ascending:false}).limit(20),
   getSupabase().from("proc_request_items").select("id,request_id,item_id,qty,note").in("request_id", (await getSupabase().from("proc_requests").select("id").eq("business_id",bu.business_id).limit(100)).data?.map((x:any)=>x.id) || ["00000000-0000-0000-0000-000000000000"]),
   getSupabase().from("proc_purchase_orders").select("id,po_number,status,total,order_date,expected_date").eq("business_id",bu.business_id).order("created_at",{ascending:false}).limit(20),
   getSupabase().from("proc_stock").select("id,item_id,outlet_id,qty").eq("business_id",bu.business_id)
  ]);
  setBusinessName(b.data?.name??"Cafe");setOutletId(o.data?.id??"");setOutletName(o.data?.name??"Outlet");
  setItems(it.data??[]);setSuppliers(s.data??[]);setRequests(r.data??[]);setRequestItems(ri.data??[]);setPos(p.data??[]);setStocks(st.data??[]);setLoading(false);
 }
 async function signIn(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");const {error:e1}=await getSupabase().auth.signInWithPassword({email,password});if(e1)setError(e1.message);setBusy(false)}
 async function signOut(){await getSupabase().auth.signOut();setUser(null)}
 async function addItem(){if(!newItem.name)return;setBusy(true);const {error:e}=await getSupabase().from("proc_items").insert({business_id:businessId,name:newItem.name,category:newItem.category,unit:newItem.unit,reorder_point:Number(newItem.reorder_point),last_cost:Number(newItem.last_cost)});if(e)setError(e.message);else{setShowItem(false);setNewItem({name:"",category:"Bahan Baku",unit:"kg",reorder_point:"0",last_cost:"0"});await load(user!)}setBusy(false)}
 async function addSupplier(){if(!newSupplier.name)return;setBusy(true);const {error:e}=await getSupabase().from("proc_suppliers").insert({business_id:businessId,name:newSupplier.name,phone:newSupplier.phone||null,lead_time_days:Number(newSupplier.lead_time_days)});if(e)setError(e.message);else{setShowSupplier(false);setNewSupplier({name:"",phone:"",lead_time_days:"1"});await load(user!)}setBusy(false)}
 async function createPO(){const req=requests.find(x=>x.id===poRequest); if(!req||req.status!=="APPROVED"||!poSupplier||!outletId)return; const ris=requestItems.filter(x=>x.request_id===poRequest); if(!ris.length)return; setBusy(true); setError(""); const lines=ris.map(x=>({item_id:x.item_id,qty:Number(x.qty),unit_cost:Number(poCosts[x.id]||0)})); if(lines.some(x=>x.unit_cost<=0)){setError("Semua unit cost PO harus diisi lebih dari 0.");setBusy(false);return;} const subtotal=lines.reduce((n,x)=>n+x.qty*x.unit_cost,0); const poNumber="PO-"+Date.now(); const {data:po,error:e}=await getSupabase().from("proc_purchase_orders").insert({business_id:businessId,supplier_id:poSupplier,outlet_id:outletId,request_id:poRequest,po_number:poNumber,status:"DRAFT",order_date:new Date().toISOString().slice(0,10),expected_date:poExpected||null,subtotal,tax:0,shipping:0,total:subtotal,notes:poNote||null,created_by:user!.id}).select("id").single(); if(e)setError(e.message); else if(po){const {error:e2}=await getSupabase().from("proc_po_items").insert(lines.map(x=>({...x,po_id:po.id,line_total:x.qty*x.unit_cost}))); if(e2)setError(e2.message); else {await getSupabase().from("proc_requests").update({status:"ORDERED"}).eq("id",poRequest);setShowPO(false);setPoRequest("");setPoSupplier("");setPoCosts({});setPoExpected("");setPoNote("");setTab("po");await load(user!)}} setBusy(false)}
 async function addRequest(){if(!reqItem||!reqQty||!outletId)return;setBusy(true);const {data:r,error:e}=await getSupabase().from("proc_requests").insert({business_id:businessId,outlet_id:outletId,requested_by:user!.id,status:"SUBMITTED",needed_date:reqDate||null,notes:reqNote||null}).select("id").single();if(e)setError(e.message);else if(r){const {error:e2}=await getSupabase().from("proc_request_items").insert({request_id:r.id,item_id:reqItem,qty:Number(reqQty)});if(e2)setError(e2.message);else{setShowRequest(false);setReqItem("");setReqQty("");setReqDate("");setReqNote("");await load(user!)}}setBusy(false)}

 const lowStock=stocks.filter(s=>{const i=items.find(x=>x.id===s.item_id);return i&&Number(s.qty)<=Number(i.reorder_point)}).length;
 const pending=requests.filter(x=>x.status==="SUBMITTED"||x.status==="APPROVED").length;
 const poValue=pos.reduce((n,x)=>n+Number(x.total||0),0);

 if(!user)return <main className="auth-shell"><section className="login-card"><div className="brand"><span className="mark">N</span><div><strong>NORTAGO</strong><small>CAFE PROCUREMENT CONTROL</small></div></div><div className="eyebrow">PROCUREMENT CAFE</div><h1>Belanja cafe.<br/><span>Terkontrol dari satu tempat.</span></h1><p className="lead">Request outlet → approval → PO → penerimaan → invoice → kontrol stok.</p><form onSubmit={signIn}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<div className="error">{error}</div>}<button disabled={busy}>{busy?"Masuk...":"Masuk ke Procurement →"}</button></form></section></main>;

 if(loading)return <main className="app-shell"><div className="loading">Memuat Procurement Cafe…</div></main>;

 return <main className="app-shell"><header className="topbar"><div className="brand"><span className="mark">N</span><div><strong>CAFE PROCUREMENT</strong><small>{businessName} · {outletName}</small></div></div><div className="userbox"><span>{user.email}</span><button className="ghost" onClick={signOut}>Keluar</button></div></header>
 <section className="hero"><div><div className="eyebrow">NORTAGO PROCUREMENT CONTROL</div><h1>Pengadaan cafe tanpa kebocoran.</h1><p>Semua pembelian dimulai dari kebutuhan nyata outlet, bukan dari keputusan supplier.</p></div></section>
 <nav className="tower-tabs">{[["dashboard","Dashboard"],["master","Item & Supplier"],["request","Purchase Request"],["po","Purchase Order"]].map(([k,v])=><button key={k} className={tab===k?"active":""} onClick={()=>setTab(k)}>{v}</button>)}</nav>
 {error&&<div className="error page-error">{error}</div>}
 {tab==="dashboard"&&<><section className="grid"><article className="metric"><div className="metric-title">ITEM AKTIF</div><div className="metric-value">{items.length}</div><div className="metric-note">Master bahan cafe</div></article><article className="metric"><div className="metric-title">LOW STOCK</div><div className="metric-value">{lowStock}</div><div className="metric-note">Perlu pengadaan</div></article><article className="metric"><div className="metric-title">REQUEST PENDING</div><div className="metric-value">{pending}</div><div className="metric-note">Menunggu proses</div></article><article className="metric"><div className="metric-title">NILAI PO</div><div className="metric-value">{money(poValue)}</div><div className="metric-note">20 PO terbaru</div></article></section>
 <section className="panels"><article className="panel"><div className="panel-head"><div><div className="eyebrow">CONTROL FLOW</div><h2>Procurement Chain</h2></div><span className="pill">LIVE DATA</span></div><div className="chain">{["Outlet Need","Request","Approval","PO","Receive","Invoice"].map((x,i)=><div className="chain-item" key={x}><b>0{i+1}</b><span>{x}</span>{i<5&&<em>→</em>}</div>)}</div><p className="method">Setiap rupiah pembelian punya alasan, dokumen, supplier, dan bukti penerimaan.</p></article>
 <article className="panel"><div className="eyebrow">RECENT REQUESTS</div><h2>Purchase Request</h2><ul className="steps">{requests.slice(0,5).map(r=><li key={r.id}><span>{r.status}</span>{r.needed_date?" · Need "+r.needed_date:""}<br/><small>{r.notes||"Permintaan pengadaan outlet"}</small></li>)}{!requests.length&&<li>Belum ada purchase request.</li>}</ul></article></section></>}

 {tab==="master"&&<section className="data-panel"><div className="split-grid"><article className="sub-panel"><div className="section-toolbar"><div><div className="eyebrow">MASTER DATA</div><h3>Item Cafe</h3><p>{items.length} item aktif</p></div><button onClick={()=>setShowItem(!showItem)}>+ Item</button></div>{showItem&&<div className="inline-form"><label>Nama<input value={newItem.name} onChange={e=>setNewItem({...newItem,name:e.target.value})}/></label><label>Kategori<input value={newItem.category} onChange={e=>setNewItem({...newItem,category:e.target.value})}/></label><label>Satuan<input value={newItem.unit} onChange={e=>setNewItem({...newItem,unit:e.target.value})}/></label><label>Reorder Point<input type="number" value={newItem.reorder_point} onChange={e=>setNewItem({...newItem,reorder_point:e.target.value})}/></label><label>Harga terakhir<input type="number" value={newItem.last_cost} onChange={e=>setNewItem({...newItem,last_cost:e.target.value})}/></label><button onClick={addItem} disabled={busy}>Simpan</button></div>}<div className="table-wrap"><table><thead><tr><th>Item</th><th>Kategori</th><th>Unit</th><th>ROP</th><th>Last Cost</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td>{i.name}</td><td>{i.category}</td><td>{i.unit}</td><td>{i.reorder_point}</td><td>{money(i.last_cost)}</td></tr>)}{!items.length&&<tr><td colSpan={5} className="empty">Belum ada item.</td></tr>}</tbody></table></div></article>
 <article className="sub-panel"><div className="section-toolbar"><div><div className="eyebrow">VENDOR</div><h3>Supplier</h3><p>{suppliers.length} supplier aktif</p></div><button onClick={()=>setShowSupplier(!showSupplier)}>+ Supplier</button></div>{showSupplier&&<div className="inline-form"><label>Nama supplier<input value={newSupplier.name} onChange={e=>setNewSupplier({...newSupplier,name:e.target.value})}/></label><label>Telepon<input value={newSupplier.phone} onChange={e=>setNewSupplier({...newSupplier,phone:e.target.value})}/></label><label>Lead time<input type="number" value={newSupplier.lead_time_days} onChange={e=>setNewSupplier({...newSupplier,lead_time_days:e.target.value})}/></label><button onClick={addSupplier} disabled={busy}>Simpan</button></div>}<div className="table-wrap"><table><thead><tr><th>Supplier</th><th>Telepon</th><th>Lead Time</th></tr></thead><tbody>{suppliers.map(s=><tr key={s.id}><td>{s.name}</td><td>{s.phone||"-"}</td><td>{s.lead_time_days} hari</td></tr>)}{!suppliers.length&&<tr><td colSpan={3} className="empty">Belum ada supplier.</td></tr>}</tbody></table></div></article></div></section>}

 {tab==="request"&&<section className="data-panel"><div className="section-toolbar"><div><div className="eyebrow">OUTLET PROCUREMENT</div><h2>Purchase Request</h2><p>Staff mengajukan kebutuhan; manager/owner mengontrol keputusan.</p></div><button onClick={()=>setShowRequest(!showRequest)}>+ Buat Request</button></div>{showRequest&&<div className="inline-form"><label>Item<select value={reqItem} onChange={e=>setReqItem(e.target.value)}><option value="">Pilih item</option>{items.map(i=><option value={i.id} key={i.id}>{i.name}</option>)}</select></label><label>Qty<input type="number" min="0.01" value={reqQty} onChange={e=>setReqQty(e.target.value)}/></label><label>Dibutuhkan tanggal<input type="date" value={reqDate} onChange={e=>setReqDate(e.target.value)}/></label><label>Catatan<textarea value={reqNote} onChange={e=>setReqNote(e.target.value)}/></label><button onClick={addRequest} disabled={busy}>Submit Request</button></div>}<div className="table-wrap"><table><thead><tr><th>Tanggal</th><th>Status</th><th>Need Date</th><th>Catatan</th></tr></thead><tbody>{requests.map(r=><tr key={r.id}><td>{new Date(r.created_at).toLocaleDateString("id-ID")}</td><td><span className="status-badge">{r.status}</span></td><td>{r.needed_date||"-"}</td><td>{r.notes||"-"}</td></tr>)}{!requests.length&&<tr><td colSpan={4} className="empty">Belum ada request.</td></tr>}</tbody></table></div></section>}

 {tab==="po"&&<section className="data-panel"><div className="section-toolbar"><div><div className="eyebrow">PURCHASE ORDER</div><h2>Purchase Order</h2><p>PO dibuat hanya dari Purchase Request yang sudah APPROVED.</p></div><button onClick={()=>setShowPO(!showPO)}>+ Buat PO</button></div>{showPO&&<div className="inline-form"><label>Approved Request<select value={poRequest} onChange={e=>{setPoRequest(e.target.value);setPoCosts({});}}><option value="">Pilih request approved</option>{requests.filter(r=>r.status==="APPROVED").map(r=><option value={r.id} key={r.id}>{r.id.slice(0,8)} · {r.notes||"Purchase Request"}</option>)}</select></label><label>Supplier<select value={poSupplier} onChange={e=>setPoSupplier(e.target.value)}><option value="">Pilih supplier</option>{suppliers.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label>{requestItems.filter(x=>x.request_id===poRequest).map(x=>{const it=items.find(i=>i.id===x.item_id);return <label key={x.id}>{it?.name||"Item"} · Qty {x.qty}<input type="number" min="0.01" placeholder="Unit cost" value={poCosts[x.id]||""} onChange={e=>setPoCosts({...poCosts,[x.id]:e.target.value})}/></label>})}<label>Expected date<input type="date" value={poExpected} onChange={e=>setPoExpected(e.target.value)}/></label><label>Catatan<textarea value={poNote} onChange={e=>setPoNote(e.target.value)}/></label><button onClick={createPO} disabled={busy}>Simpan PO</button></div><div className="table-wrap"><table><thead><tr><th>PO</th><th>Status</th><th>Order Date</th><th>Expected</th><th>Total</th></tr></thead><tbody>{pos.map(p=><tr key={p.id}><td><b>{p.po_number}</b></td><td><span className="status-badge">{p.status}</span></td><td>{p.order_date}</td><td>{p.expected_date||"-"}</td><td>{money(p.total)}</td></tr>)}{!pos.length&&<tr><td colSpan={5} className="empty">Belum ada PO. PO dibuat setelah request disetujui.</td></tr>}</tbody></table></div></section>}

 <footer>Powered by <b>NORTAGO</b> · Cafe Procurement Control · Supabase RLS</footer></main>
}
