"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import {createClient} from "@supabase/supabase-js";
type Mode="TAKE_AWAY"|"PRE_ORDER"|"DELIVERY";
type Product={id:string;name:string;price:number;cat?:string;desc?:string;image_url?:string|null};
type Outlet={id:string;business_id:string;name:string};
type CartItem={key:string;product:Product;qty:number;variant:string;addons:{name:string;price:number}[]};
async function getSupabase(){const r=await fetch("/api/supabase-config",{cache:"no-store"});const c=await r.json().catch(()=>({}));if(!r.ok||!c.url||!c.key)throw new Error(c.error||"Supabase runtime configuration is not available.");return createClient(c.url,c.key);}
export default function CustomerOrder(){
 const[mode,setMode]=useState<Mode>("TAKE_AWAY");const[outlets,setOutlets]=useState<Outlet[]>([]);const[outletId,setOutletId]=useState("");const[products,setProducts]=useState<Product[]>([]);const[cart,setCart]=useState<CartItem[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
 useEffect(()=>{(async()=>{try{const s=await getSupabase();const [{data:o,error:oe},{data:p,error:pe}]=await Promise.all([s.from("otc_outlets").select("id,business_id,name").eq("is_active",true).order("name"),s.from("otc_products").select("id,name,description,category,image_url,base_price").eq("is_active",true).order("name")]);if(oe)throw oe;if(pe)throw pe;setOutlets(o||[]);setOutletId(o?.[0]?.id||"");setProducts((p||[]).map(x=>({id:x.id,name:x.name,price:Number(x.base_price||0),cat:x.category,desc:x.description,image_url:x.image_url})));}catch(e:any){setError(e.message||"Gagal memuat menu.");}finally{setLoading(false)}})()},[]);
 const outlet=outlets.find(o=>o.id===outletId);const available=useMemo(()=>products,[products]);
 const add=(p:Product)=>setCart(c=>{const key=p.id+"|Default";const hit=c.find(i=>i.key===key);if(hit)return c.map(i=>i.key===key?{...i,qty:i.qty+1}:i);return [...c,{key,product:p,qty:1,variant:"Default",addons:[]}]});
 const change=(key:string,d:number)=>setCart(c=>c.map(i=>i.key===key?{...i,qty:i.qty+d}:i).filter(i=>i.qty>0));
 const total=useMemo(()=>cart.reduce((n,i)=>n+i.product.price*i.qty,0),[cart]);
 const goCheckout=()=>{sessionStorage.setItem("otc_cart",JSON.stringify(cart));sessionStorage.setItem("otc_outlet_id",outletId)};
 if(loading)return <main className="otc-page"><div className="loading">Memuat menu…</div></main>;
 if(error)return <main className="otc-page"><div className="info-box wide">{error}</div></main>;
 return <main className="otc-page"><header className="otc-head"><div><b>NORTAGO OTC</b><small>Customer Mini App · {outlet?.name||"Outlet"}</small></div><Link href="/otc">Home</Link></header>
 <section className="customer-title"><span>ORDER ONLINE</span><h1>Menu & Checkout</h1><p>Menu dan harga dibaca langsung dari OCT System of Record.</p><label style={{display:"inline-grid",gap:6,marginTop:15,color:"#9db2ae",fontSize:12}}>Outlet<select value={outletId} onChange={e=>setOutletId(e.target.value)} style={{background:"#081417",border:"1px solid #294447",color:"#e9f1ef",borderRadius:9,padding:"10px 12px"}}>{outlets.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label></section>
 <div className="mode-grid otc-mode">{[["TAKE_AWAY","Take Away","Ambil segera"],["PRE_ORDER","Pre-Order","Jadwal hari/tanggal"],["DELIVERY","Delivery","Kurir pihak ketiga"]].map(([m,t,s])=><button type="button" className={mode===m?"active-mode":""} onClick={()=>setMode(m as Mode)} key={m}><b>{t}</b><small>{s}</small></button>)}</div>
 <section className="otc-shop"><div className="menu-panel"><div className="section-head"><div><span className="eyebrow">MENU</span><h2>Produk & Harga</h2></div><span className="pill">Live</span></div>
 {available.map(p=><article className="product-card" key={p.id}><div className="product-photo">{p.image_url?<img src={p.image_url} alt={p.name}/>: "PHOTO"}</div><div className="product-info"><small>{p.cat||"Product"}</small><h3>{p.name}</h3><p>{p.desc||"Produk OCT"}</p><b>Rp {p.price.toLocaleString("id-ID")}</b></div><button type="button" className="otc-secondary" onClick={()=>add(p)}>+ Tambah</button></article>)}</div>
 <aside className="cart-panel"><span className="eyebrow">CART</span><h2>Pesanan Anda</h2>{cart.length===0?<p className="muted">Belum ada produk.</p>:cart.map(i=><div className="cart-line" key={i.key}><span>{i.product.name} × {i.qty}</span><div style={{textAlign:"right"}}><b>Rp {(i.product.price*i.qty).toLocaleString("id-ID")}</b><div className="qty"><button type="button" onClick={()=>change(i.key,-1)}>-</button><span>{i.qty}</span><button type="button" onClick={()=>change(i.key,1)}>+</button></div></div></div>)}<div className="total-line"><span>Subtotal</span><strong>Rp {total.toLocaleString("id-ID")}</strong></div><Link onClick={goCheckout} className={"otc-primary full "+(!cart.length?"disabled":"")} href={cart.length?"/otc/checkout?mode="+mode:"#"}>Lanjut Checkout →</Link>
 {mode==="PRE_ORDER"&&<div className="info-box">PO: pilih jadwal di checkout. H-1 ada konfirmasi jadwal.</div>}{mode==="DELIVERY"&&<div className="info-box">Delivery memakai kurir pihak ketiga.</div>}{mode==="TAKE_AWAY"&&<div className="info-box">Pickup Pass dibuat setelah order tercatat.</div>}</aside></section><footer>Supported by NORTAGO · OCT System of Record</footer></main>
}