"use client";
export const dynamic="force-dynamic";
import {useEffect,useState} from "react";
import {createClient,type User} from "@supabase/supabase-js";
const sb=()=>createClient(process.env.NEXT_PUBLIC_SUPABASE_URL||"https://placeholder.supabase.co",process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY||"placeholder");
const money=(n:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n);
export default function ReceivingPage(){
 const s=sb(); const [user,setUser]=useState<User|null>(null),[businessId,setBusinessId]=useState(""),[outletId,setOutletId]=useState(""),[pos,setPos]=useState<any[]>([]),[items,setItems]=useState<any[]>([]),[selected,setSelected]=useState<any|null>(null),[qty,setQty]=useState<Record<string,string>>({}),[receiptNo,setReceiptNo]=useState(""),[note,setNote]=useState(""),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
 async function load(u:User){const {data:bu}=await s.from("business_users").select("business_id").eq("user_id",u.id).limit(1).maybeSingle();if(!bu)return;setBusinessId(bu.business_id);const {data:o}=await s.from("otc_outlets").select("id").eq("business_id",bu.business_id).eq("is_active",true).limit(1).maybeSingle();setOutletId(o?.id||"");const {data:p}=await s.from("proc_purchase_orders").select("id,po_number,supplier_id,outlet_id,status,order_date,expected_date,total").eq("business_id",bu.business_id).in("status",["DRAFT","APPROVED","ORDERED","PARTIAL"]).order("created_at",{ascending:false});setPos(p||[]);const {data:i}=await s.from("proc_items").select("id,name,unit").eq("business_id",bu.business_id).eq("is_active",true).order("name");setItems(i||[]);}
 useEffect(()=>{s.auth.getSession().then(({data})=>{if(data.session){setUser(data.session.user);load(data.session.user)}})},[]);
 async function receive(){if(!selected||!businessId||!outletId||!receiptNo)return;const lines=selected.lines as any[];const values=lines.map(x=>({po_item_id:x.id,qty_received:Number(qty[x.id]||0)}));if(values.some(x=>x.qty_received<0)||values.every(x=>x.qty_received===0)){setMsg("Isi minimal satu qty penerimaan.");return}setBusy(true);setMsg("");const {data:r,error:e}=await s.from("proc_receipts").insert({business_id:businessId,po_id:selected.po.id,outlet_id:selected.po.outlet_id||outletId,received_by:user?.id||null,receipt_number:receiptNo,notes:note||null}).select("id").single();if(e){setMsg(e.message);setBusy(false);return}const {error:e2}=await s.from("proc_receipt_items").insert(values.filter(x=>x.qty_received>0).map(x=>({receipt_id:r.id,po_item_id:x.po_item_id,qty_received:x.qty_received,accepted:true})));if(e2){setMsg(e2.message);setBusy(false);return}for(const x of values.filter(x=>x.qty_received>0))await s.from("proc_po_items").update({received_qty:Number((lines.find(y=>y.id===x.po_item_id)?.received_qty||0))+x.qty_received}).eq("id",x.po_item_id);await load(user!);setSelected(null);setQty({});setReceiptNo("");setNote("");setMsg("Penerimaan berhasil. WAC dan stock diproses otomatis oleh trigger.");setBusy(false)}
 async function pick(po:any){const {data:pi}=await s.from("proc_po_items").select("id,item_id,qty,unit_cost,received_qty").eq("po_id",po.id);setSelected({po,lines:pi||[]});}
 return <main style={{maxWidth:1100,margin:"40px auto",padding:24,fontFamily:"system-ui"}}><h1>NORTAGO Receiving</h1><p>PO → Receiving → Weighted Average Cost → Stock.</p>{msg&&<div style={{padding:12,margin:"12px 0",border:"1px solid #ccc"}}>{msg}</div>}<h2>Open PO</h2>{pos.length===0?<p>Belum ada PO yang siap diterima.</p>:<table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr><th align="left">PO</th><th>Status</th><th>Expected</th><th>Total</th><th></th></tr></thead><tbody>{pos.map(p=><tr key={p.id}><td>{p.po_number}</td><td>{p.status}</td><td>{p.expected_date||"-"}</td><td>{money(p.total)}</td><td><button onClick={()=>pick(p)}>Terima</button></td></tr>)}</tbody></table>}{selected&&<section style={{marginTop:24,padding:20,border:"1px solid #ddd"}}><h2>Penerimaan {selected.po.po_number}</h2><label>Receipt Number <input value={receiptNo} onChange={e=>setReceiptNo(e.target.value)} placeholder="GRN-..." /></label><div>{selected.lines.map((x:any)=>{const it=items.find(i=>i.id===x.item_id);const remaining=Math.max(0,Number(x.qty)-Number(x.received_qty||0));return <div key={x.id} style={{display:"grid",gridTemplateColumns:"2fr 1fr 1fr",gap:12,margin:"14px 0"}}><span>{it?.name||x.item_id} · {it?.unit||""}</span><span>Open {remaining}</span><input type="number" min="0" max={remaining} value={qty[x.id]||""} onChange={e=>setQty({...qty,[x.id]:e.target.value})} placeholder="Qty received"/></div>})}</div><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Catatan / kondisi barang" style={{width:"100%",minHeight:70}}/><br/><button disabled={busy} onClick={receive}>{busy?"Memproses...":"Simpan Penerimaan"}</button> <button onClick={()=>setSelected(null)}>Batal</button></section>}<footer style={{marginTop:40}}>Powered by <b>NORTAGO</b></footer></main>
}